### ISSUE TITLE
ServiceMonitor for Collabora

### ISSUE THREAD

**Issue by genofire** [chrisingenhaag/helm#23]
If possible / enabled, it would be nice to install a ServiceMonitor for PrometheusOperator.

/cool/getMetrics` is the url for it with BasicAuth of your Variable.

```yaml
apiVersion: monitoring.coreos.com/v1                                                                                                                                                                              kind: ServiceMonitor                                                                                                                                                                                              metadata:
  spec:
    endpoints:
      - port: "http"
        path: "/cool/getMetrics"
        basicAuth:
          username:
            name: "{{ include "collabora-code.fullname" . }}"
            key: username
          password:
            name: "{{ include "collabora-code.fullname" . }}"
            key: password
    selector:
      matchLabels:
        app.kubernetes.io/name: {{ include "collabora-code.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}   
```
